language: ruby
cache: bundler
rvm:
  - ruby-head
  - 2.4.1
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby-9.1.14.0
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails5.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails4.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
env:
  global:
    - JRUBY_OPTS='--debug'
before_install:
  - gem install bundler
  - sudo apt-get -y remove memcached
  - echo "yes" | sudo add-apt-repository ppa:travis-ci/memcached-sasl
  - sudo apt-get update
  - sudo apt-get install -y memcached=1.4.13-0ubuntu2+travis1
