language: ruby
cache: bundler
rvm:
  - 2.2.3
  - 2.1
  - 2.0.0
  - 1.9.3
  - rbx-2
  - jruby
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.3
      gemfile: gemfiles/rails3.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: rbx-2
env: JRUBY_OPTS='--1.9'
before_install:
  - sudo apt-get -y remove memcached
  - echo "yes" | sudo add-apt-repository ppa:travis-ci/memcached-sasl
  - sudo apt-get update
  - sudo apt-get install -y memcached=1.4.13-0ubuntu2+travis1
