language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode
  - jruby
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4.gemfile
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-18mode
    - rvm: rbx-19mode
  exclude:
    # Rails4 requires Ruby >= 1.9.3
    - rvm: 1.8.7
      gemfile: gemfiles/rails4.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails4.gemfile
    - rvm: ree
      gemfile: gemfiles/rails4.gemfile
    - rvm: rbx
      gemfile: gemfiles/rails4.gemfile
    - rvm: rbx-18mode
      gemfile: gemfiles/rails4.gemfile
branches:
  only:
    - master
env: JRUBY_OPTS='--1.9'
